services:
  - type: web
    name: blackout
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/blackout-1.0.0.jar --spring.profiles.active=render"
    healthCheckPath: /index.html
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render

databases:
  - name: blackout-db
    plan: free
    databaseName: blackout
