services:
  - type: web
    name: blackout
    env: docker
    plan: free
    healthCheckPath: /index.html
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render

databases:
  - name: blackout-db
    plan: free
    databaseName: blackout
